---
title: ""
output:
  html_document:
    theme: yeti
    sansfont: Georgia
    df_print: paged
    Highlight: Tango
    
    css: styles.css


---

<br>
<br>

<h1>**Makhia Bryant**</h1> 
<h6>
***A text message to a friend on gun violence and policing.***
</h6>

04/22/2021
 <br>
  
  Everywhere is Nowhere

If you have the desire to become fully anonymous and untraceable, it would be best to use an untraceable linux iso like Tails, the very operating system Edward Snowden

[uses](https://news.softpedia.com/news/Edward-Snowden-Used-the-Tails-Linux-Distro-to-Stay-Hidden-438074.shtml). The next best thing might be to de-google your life, as Google is the most pervasive tracking software out there. Gmail, YouTube, Maps, Docs, Apps, let alone many of our usernames to everything, it can be overwhelming even conceptualizing a life without google, but it can be done, and arguably should be done. However, that is not our mission today. Today we will provide 77 ways to bolster your online and offline experience from both a security and a privacy perspective.

  

Level: Beginner

  

  

  

Computer

All suggestions will apply to both Apple and Windows based Operating systems though apple has a better track record here.

  

1 - Use a privacy browser like Brave

2 - Use an anti tracking extension

3 - Use an adblocker

4 - Browse in private mode

5 - Use built in Tor router when possible

6 - Use a privacy search engine like Duck Duck go

7 - Use separate passwords for every login

8 - Never allow your apps to remember passwords

9 - Never install an application that can be used online

10 - Never install anything you don't need

11 - Never click an unknown link

12 - Be aware of popups

13 - Be conscious of where you click

14 - Use 2FA when it counts

15 - Avoid syncing

16 - Choose not to store cookies, or delete them frequently

17 - Choose not to cache any websites, or delete frequently

18 - Use a VPN

19 - Don't use public wifi

20 - Tether to your phone if needed

21 - Back up your data

22 - Encrypt your data where possible

23 - Disable bluetooth when not using

24 - Use a hardware wallet for crypto assets 

  

Mobile

All suggestions will apply to both apple and android though apple has a better track record here.

  

34 - Use a passcode

35 - Lock when not in use

36 - Call your carrier and have them prevent sim swapping

37 - Don't download third party apps

38 - Beware of clicking random links

39 - Back up your data

40 - Encrypt your data when possible

41 - Use a privacy messenger like signal

42 - Enable 2FA

43 - Don't root or jailbreak

44 - Keep your phone up to date

45 - Use fingerprint and facial scanners

46 - Don't give apps access to any other apps

47 - Install as few apps as possible

48 - Don't allow apps to track you

49 - Turn off location services

50 - Revoke apps access to your location and other information

51 - Turn off wifi when not in use

52 - Turn off Bluetooth when not in use

53 - Limit ad tracking if possible

54 - Install a VPN if possible

55 - Don't share your data with your service provider

  

  

Travel

Privacy and security is even more important when traveling.

  

67 - Don't connect to public wifi

68 - Tether to your phone

69 - Use a VPN

70 - Use passcodes on your devices

71 - Be mindful of where you're accessing your devices

72 - Don't use public computers

73 - Don't use printers or connected devices

74 - Use an RFID blocking wallet

75 - Consider a privacy filter

76 - Leave devices in secure locations

77 - Be mindful


<br>