---
title: ""
output:
  html_document:
    theme: yeti
    sansfont: Georgia
    df_print: paged
    Highlight: Tango
    
    css: styles.css


---

<br>
<br>

<h1>**Distributed Idea Suppression Complex**</h1> 
<h6>
***An article by Tyler Young.***
</h6>

*[Tylerisyoung.Substack.com](www.tylerisyoung.substack.com)*   
*[Twitter.com/TylerisYoung](www.twitter.com/Tylerisyoung)*  
 _________________________
 <br>
 11/02/2021
 <br>
 
<h3>
Is information disseminated fairly?
</h3>


<br>
Universities, institutions, and the academic journals are playing the same bureaucratic institutional role that mainstream news organizations are; Suppressing new ideas in favor of tenure tracks, published research, and a cheap labor force doing the highest caliber work in the form of workers who are not tied into the distributed network of mainstream enforcement. Those who are detached include up and coming PHD students, blue collar workers, independent journalists, eager start up entrepreneurs, and the like, being largely the only ones capable of producing original thoughts, ideas, and solving problems in novel ways. They continue their paths thanklessly only to have their concerns silenced, shot down, and canceled, while their best original thoughts and ideas are stolen from under them and taken credit for by the established institutional players. This is not a new phenomenon. 

  

Dr Eric Weinstein coined the term [Distributed Idea Suppression Complex ](https://medium.com/@josephparrish/encountering-the-disc-in-democratic-party-da7df9efd7aa)  the (DISC) has arisen and has a competitive advantage in every major society and sector until this phenomenon is either corrected to a mode that benefits a majority of society, or destroyed. The only downfall of the amorphous driving force of the DISC may come from public uprising; Unions and grad students on strike, political corruption that's become too blatant to ignore, war, or depending on how you view it, the unnerving, or inevitable rise of former president Donald Trump.

  

Over the last 50 years we have seen an unprecedented shift from the traditional economic bell curve of wealth distribution to more of a negatively skewing, bottom weighted Lorenz curve of economic inequality where the 1% thrive. This is not inherently bad, nor unexpected, but has negative consequences when it's reinforced by corruption and politicians who not only favor the elite, but who are the elite. This influence can then be used to manipulate what should be free market capitalism with delicate regulation and has lead us to a place many call [late stage capitalism](https://en.wikipedia.org/wiki/Late_capitalism). Our elected representatives are openly corrupt, Nanci Pelosi is the third richest individual in Congress with a net worth of $120 million from a salary of $223k/ year. In addition to her salary over her 18 years in congress, she outperformed the market by a factor of 10 averaging 27% per year doing better than Warren Buffet himself.

 

There have recently been [accusations](https://www.forbes.com/sites/jackkelly/2020/03/20/senators-accused-of-insider-trading-dumping-stocks-after-coronavirus-briefings/#31ff28b94a45) of insider trading in congress, but this is nothing new considering the house speaker’s [precedent](https://www.cbsnews.com/news/congress-trading-stock-on-inside-information/) of great stock picks: 5000 shares of VISA which she just so happened to buy while legislation that would have hurt credit card companies was likely to pass in the house, after her purchases were made public, the stock jumped an unprecedented 68% in two days, and the bill never made it to the floor.

  

Our institutions are objectively corrupt, and the incentive structures of the DISC perpetuate this corruption out in the open, only to be later justified and greenwashed by the media and useful idiots. This is why a majority of Americans do not vote, or refuse to participate. This is also why it lands when people like Donald Trump called the democrats corrupt and calls out the fake news. We can’t pretend it’s not there on both sides, but I think Donald Trump made a great litmus test for objectivity.

  

I was not around for the mystical Clinton years, but I refuse to believe that Joe Biden and the modern democratic party are Jesus reincarnate. While living in California, I have been “accused" of being a Republican as if vote shaming someone was ever a good thing, so I will also add that I do not believe anyone, especially a leader, should ever be as brazen and crass as Trump was, no one should lie so much about anything let alone things which don’t even matter, he should not have been overtly racist, he should stop getting fake tans etc. etc. but my position is that; Trump was the best example i've seen of the DISC in action when it came to things like the false narratives of [Russiagate](https://taibbi.substack.com/p/the-russiagate-whitewash-era-begins?token=eyJ1c2VyX2lkIjo4Nzc1MjUyLCJfIjoiUk1OMU0iLCJpYXQiOjE2MzgxNzAyMTksImV4cCI6MTYzODE3MzgxOSwiaXNzIjoicHViLTEwNDIiLCJzdWIiOiJwb3N0LXJlYWN0aW9uIn0.RFCpH47ca_L0TI7DuHBgeCdBUrK376PaUBbl32Xd7gM), [Ukrainegate](https://www.sgtreport.com/2019/11/the-real-story-behind-ukrainegate/), and the majority of his presidency which was lies on all sides which were easy to see if you don't pledge allegiance to one side or the other.



Similar false narratives are present within the Covid lab leak hypothesis, at first those who even mentioned it were called [conspiracy theorists](https://www.forbes.com/sites/startswithabang/2021/06/03/the-wuhan-lab-leak-hypothesis-is-a-conspiracy-theory-not-science/), even [racists](https://www.nationalreview.com/2021/06/the-lab-leak-theory-is-unbearably-racist/). Now it is[ widely accepted](https://unherd.com/2021/08/did-the-new-york-times-stifle-lab-leak-debate/) that it is one possible origin of many, though at this time I believe that there is [sufficient](https://nypost.com/2021/10/10/the-lab-leak-theory-is-now-almost-certainly-proved-and-other-commentary/) and continually emerging [evidence](https://www.washingtonpost.com/health/2021/08/25/coronavirus-origin-report-/) and [shifting narrative](https://www.msn.com/en-us/health/medical/more-evidence-that-the-wuhan-lab-leak-theory-is-the-correct-one/ar-BB1gtFWK) spear headed by Yuri Deigin's initial [report](https://yurideigin.medium.com/lab-made-cov2-genealogy-through-the-lens-of-gain-of-function-research-f96dd7413748) which suggests that a lab leak would be not only the Occam's razor conclusion, but is provably the only possible origin of Sars Cov-2. This of course will never be confirmed or publicly shared by any major news networks, or even by governments continually worried about international push back, because the DISC in all its forms buries inconvenient truths despite how much harm they may cause. Could lives have been saved if we focused on facts instead of censorship and manipulation?

  
  

Neither the left or the right, nor Trump nor Biden is the root of the problem, corrupt politicians are a symptom of the problem. The problem is in part a financial one as explained by [Chomsky](https://en.wikipedia.org/wiki/Manufacturing_Consent), but it is also a philosophical one. We need an exit from our now entrenched us vs. them mentality, our identity politics and our newly adopted woke culture wars cannot sustain. Yes, we need to trust the science, but we also need to ensure that media and academic institutions are not self censoring the science for political reasons.



  
 In the British Medical Journal, an opinion piece titled "[Political censorship in academic journals sets a dangerous new precedent](https://blogs.bmj.com/bmj/2021/06/02/political-censorship-in-academic-journals-sets-a-dangerous-new-precedent/)" details the political nature of a choice Lancet made to retract the authors paper warning of Covid on the war torn Gaza strip efore the virus had spread worldwide. Physicians from the U.S. and elsewhere demanded to Lancet that they remove the BMJ's article from their database and Lancet complied, explaining to BMJ that they "could not sustain yet another campaign of this nature." 
 
 
 
 The same can be said for  censorship campaigns in the name of combating misinformation on social media, facebook was forced to [retract](https://munrkazmir.medium.com/censorship-of-covid-lab-leak-theory-humiliates-social-media-giants-c50727db8b73) their ban of any mentions of the lab leak hypothesis, twitter implimented a controversial misinformation [label](https://abcnews.go.com/Technology/wireStory/twitter-rolls-redesigned-misinformation-warning-labels-81212172) and YouTube is rather [liberal](https://www.lifesitenews.com/news/youtube-bans-frontline-doctors-speech-criticizing-experimental-agent-covid-vaccine/) with their permanent banning policy towards actual doctors with different opinions. Even if these doctors in question were wrong on their analysis, how and when did social media companies determine that they know better then practicing clinicians? Do these companies have teams of medical researchers determining what is or isn't misinformation? They certainly don't simply go off of what the CDC's official policy is as evidenced by Dr. Pierre Cory's testimony to congress on the official US government Youtube channel being [taken down](https://www.foxnews.com/politics/youtube-remove-doctor-senate-testimony-coronavirus-ron-johnson-big-tech) without explication. The subject of the testimony was at the time regarding a cheap, off the shelf, and widely available drug which was potentially useful  in the treatment of covid, Ivermectin. The testimony was prior to the CDC having any guidelines regarding the drug, therefore YouTube apparently bases its censorship decisions on some other internal policy which we are unable to know, similar to the algorithms of many major social media platforms. 
 
 
 
 The same thing occurred to popular outsiders running in the 2020 election, the [Yang](https://vocal.media/theSwamp/a-visual-history-of-the-yang-media-blackout) media blackout was apparent and similar to the [Tulsi](https://www.inquisitr.com/5772836/tulsi-gabbard-media-blackout/) Media Blackout all of which are [explained](https://thehill.com/opinion/campaign/460224-why-the-media-dislike-andrew-tulsi-bernie-and-marianne) by The Hill. Our very own institutions are clinging to power with every trick in the book, and with the recent pervasiveness of social media, we can see the corruption blatantly.
 
 
 
 
 The NY Post, a now conservative outlet ,was founded by Alexander Hamilton in 1801,  today it holds the title of the Nations oldest newspaper. The paper had its official, verified account banned from twitter for breaking a story regarding Hunter Biden's Laptop. Twitter also depopulated posts and placed misinformation tags below any mentions of the laptop. Facebook did the same. The images were leaked and the story turned out weeks later to be true. The Bidens have to this day not denied the laptops existence or contents, however was rarely discussed by other outlets because the DISC favors silence when it comes to those inconvenient truths. Only weeks before the election, it could be argued this act of censorship may have changed the course of history. 
 
 
 
 
 Twitter's CEO Jack Dorsey has recently resigned and appointed a the CEO Parag Arawal who said regarding free speech, "Our role is not to be bound by the First Amendment, but our role is to serve a healthy public conversation and our moves are reflective of things that we believe lead to a healthier public conversation. The kinds of things that we do about this is, focus less on thinking about free speech, but thinking about how the times have changed. One of the changes today that we see is speech is easy on the internet. Most people can speak. Where our role is particularly emphasized is who can be heard." With this ominous attitude, Arawal alludes to a world were the constitution and freedom of the press does not hold any water online. 
 
 In his first day as CEO, Arawal announced in a [blog post](https://blog.twitter.com/en_us/topics/company/2021/private-information-policy-update) that Twitter would be implementing a new policy which prevents people from sharing photos and videos of other people without their consent if the images are intended to harass, or intimidate them. A twitter review team will assess whether the context and images violate the terms and conditions. The company claims that the policy is meant to protect people from physical or emotional harm. Emotional harm is real harm caused by real violence, and according to Berkeley [students](https://twitter.com/SophiaLeeHyun/status/908506014038630400?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E908506014038630400%7Ctwgr%5E%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fwelovetrump.com%2F2020%2F06%2F13%2Faccording-to-the-left-speech-and-silence-are-both-violence%2F), and much of the woke left; "Speech is violence" and problematic speech must also be banned. 
 
 The claim that Donald Trump incited violence with this specific tweet on January 6th got him banned from Twitter as [demanded](https://www.theverge.com/2021/1/8/22221386/twitter-employees-trump-ban-internal-letter-capitol-attack) by hundreds twitter employees. 
 
 
 This was all happening while the official Taliban [account](https://twitter.com/Zabehulah_M33) remains active bragging about their wars waged across Afghanistan and inciting violence against women. The problem with this type of enforcement is that it can never be objective. 
 
 
 Many fail to realize that this is exactly the aim, to remove objectivity, and allow those with institutional power to set the narrative based on whatever reparations they deem necessary based on a racist culture scorecard of oppression, whoever is most opressed gets precedent, this is how the "black lives matter" turned into "black trans lives matter" 
 
 This phrasing becomes worrisome when emotional harm can only be inferred. Furthermore we are increasingly seeing the so called woke portion of the democratic party claiming that "speech is violence" 
and comparing  
 
 
 Many conservatives argue that the tech giants are private companies with no obligations towards free speech and can therefore police their platforms however they desire. This argument however cannot simultaneously be used while these same platforms are protected under [Section 230](https://crsreports.congress.gov/product/pdf/R/R45650) which prevents civil or criminal lawsuits against them for what is posted on their platforms. It is also highly problematic when press secretary Jen Psaki says that the Biden administration is "[working with](https://www.thenationalsentinel.com/2021/07/15/jen-psaki-admits-that-yes-the-biden-regime-is-working-with-facebook-social-media-to-flag-content/)" social media companies to determine what content is flagged as misinformation. 


 
 This behavior is unacceptable especially when the timely spread of information could save thousands, or millions of lives, a bright and shining example of constructive policy was demonstrated by Medrxiv and other pre-print medical journal servers who in the early days of the pandemic open sourced all of their soon to be published works. The entire website came with an inherent disclaimer of: These papers are pending peer review, so they should be taken with a grain of salt. The public should be treated as if they are capable of critical thinking and rationality, rather than a herd of sheep in need of coddling. 
  


Ultimately we need corruption and perverse incentive structures out of our politics and academic institutions. Until this occurs, we need free to strike a balance that is very near to speech across social platforms so that we may collectively advocate against those very same incentives which drive the false narrative conversations. It will save lives both right now, and into the future.


  
The structural and financial problems in the media will need to be dealt with, but for now it is important that the average person knows that there is more to the news than just the fairway of mainstream information. The mainstream news will not dive into the weeds because it gets too complex and nuanced for a five minute news segment far too quickly. Therefore social media needs to remain the testing ground for information dissemination, free, and open to discussing problems that can then filter into a wider fairway of mainstream ideas, and solutions without fear of cancellation or censorship. When we as a society fear to speak out or are otherwise prevented from doing so, we are inevitably helping the DISC manufacture consent.



 Neither the government or private companies should be the arbiters of truth, truth is derived through decentralized consensus mechanisms that facilitate the scientific method of understanding where hypotheses become models and experiments which can then be replicated, those replicated studies provide information which can become a widely distributed theory, and if proven to be correct, a theory can become fact. 



I may be wrong, I hope that I am wrong, but I am afraid that I am not. We need to fight for whatever truths we have, we need to retain our open access to the internet, to a censorship free world without coercion, and to a world which strives for equal opportunity regardless of politics, and despite diverse circumstances.




-Tyler   
@TylerisYoung