---
title: "Using GREP on Nonprofit Missions"
author: ""
date: ""
output:
  html_document: 
    theme: cosmo
    highlight: haddock
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library ( dplyr )
library ( pander )
library( tidytext )
library (stringr )

```


```{r}
#IRS 1023 DATA
#Load data 
URL <- "https://github.com/DS4PS/cpp-527-spr-2020/blob/master/labs/data/IRS-1023-EZ-MISSIONS.rds?raw=true"

dat <- readRDS(gzcon(url( URL )))

head( dat[ c("orgname","codedef01","mission") ] ) %>% pander()

```

# Part 1: Patterns 
```{r, eval=FALSE}
#Example Pattern
grep(  pattern="some.reg.ex", x="mission statements", value=TRUE )
```
# Missions with Numbers 
```{r}
#Missions with numbers
grep( pattern="[0-9]", x=dat$mission, value=TRUE ) %>% head() %>% pander()

```

```{r}
# Sum of missions with numbers
grepl( "[0-9]", dat$mission ) %>% sum()
```
<h2>
1. Filter by: Starts with "to"
</h2>
```{r}
#How many begin with "to"
filter_to <- grep( "to" , x=dat$mission, value=TRUE )
head(filter_to, 6 ) %>% pander()
```

```{r}
filter_to <- grepl( "to" , x=dat$mission ) 
sum(filter_to)
```

<h2>
2. Filter by: blank mission statements
</h2>

```{r}
#Orgs by number which have blank missino statements
filter_blank <- grep("^[[:space:]]*$",x=dat$mission)
#subset(dat,!grepl("^[[:space:]]*$", mission))
#dat[which(dat$mission!=""),]
head(filter_blank , 6 )
#returns first 6 
```

```{r}
#Sum of blank mission statement orgs
filter_blank <- grep("^[[:space:]]*$",x=dat$mission)
sum(filter_blank)
```
<h2>
3. Filter by: Mission statements with trailing whitespace
</h2>
```{r}
#Identify trailing whitespace
filter_blank_end <- grepl("[[:space:]]+$", x=dat$mission) #Blankk space at all?
#filter_spaces_after <- grep("[[:space:]]+$", dat$mission) # Blank space after 

sum(filter_blank_end)

```
Trim Trailing Whitespace:
```{r}
#Trim trainling whitespace
trim_final_spaces <- function (x=dat$mission) sub("\\s+$", "", x)
trim_final_spaces() %>% head(6) %>% pander()

```
<h2>
3. Filter by: How many missions have a dollar sign
</h2>
```{r}
filter_dollar <- grepl( "$" , x=dat$mission ) 
sum(filter_dollar)
```
