---
title: ""
output:
  html_document:
    theme: yeti
    sansfont: Georgia
    df_print: paged
    Highlight: Tango
    
    css: styles.css


---

<br>
<br>

<h1>**Gendered and Racialized Buzzwords**</h1> 
<h6>
***Should I use the term LatinX?***
</h6>

*[Tylerisyoung.Substack.com](www.tylerisyoung.substack.com)*   
*[Twitter.com/TylerisYoung](www.twitter.com/Tylerisyoung)*  
 _________________________
 <br>
 06/15/2020
 <br>

<h3>
Gendered and Racialized Buzzwords
</h3>
Should I use the term LatinX?
<br>



Should I use the term LatinX? The Activist might ask. My answer is no, primarily because even [mainstream media outlets](https://www.nbcnews.com/think/opinion/many-latinos-say-latinx-offends-or-bothers-them-here-s-ncna1285916) like NBC say that it's probably not a good idea. Furthermore there was a recent study stating that of 800 registered voters of Latin American descent, only 2% chose to describe themselves as LatinX, but also that 40% of these same voters were [actively offended](https://www.politico.com/news/2021/12/06/hispanic-voters-latinx-term-523776) by the term, and 30% would not support a politician or organization using the term.

So why is this term still being advocated for and used? Because virtue signaling has become a necessity of the woke left's movement. For those who aren't interested in the following narrative and history lesson; The only way to counter postmodernism is unfortunately with more postmodernism: Is not the predominantly western and white insistence on using the term Latinx simply another form of colonization and exclusion via the English language i.e. Just another barrier to entry into a more virtuous ingroup that actually in practice excludes the very people it aims to help?

Similar to using "they" as a direct pronoun, LatinX just doesn't work for the invented problem it's meant to be solving. The entire Spanish language is gendered, and on top of that, [Politico](https://www.politico.com/news/2021/12/06/hispanic-voters-latinx-term-523776) even writes, "some Spanish speakers argue it's tricky to know how to pronounce LatinX in their native tongue". So to the people arguing for the use of this term, good luck living life thinking that an entire root language it is something that needs to be changed or “fixed” and that you know better. Terms like LatinX are not actually the end goal of the organizers of the modern left, this is a weird and tangential symptom of a larger problem, and why it's important to discuss postmodernism for what it is. Today's Postmodernism is justified racism and sexism based on the idea that governments, activists, and organizers know how to better run society compared to the traditional free markets and merit based enlightenment and scientific values. 

Racial discrimination is actually making a comeback, though not in the way you might think. Despite a multi decade long Democratic super majority, California has not done much of anything to fix any of these perceived social issues, and many of them are getting worse. The current tactic among activists is to repeal things like Prop 209 which [passed in 1996](https://ballotpedia.org/California_Proposition_209,_Affirmative_Action_Initiative_(1996)):

*"A "yes" vote supported adding Section 31 to the California Constitution's Declaration of Rights, which said that the state cannot discriminate against or grant preferential treatment on the basis of race, sex, color, ethnicity, or national origin in the operation of public employment, public education, and public contracting."*

Social Justice activists in California actually want to repeal this language - Allowing public employers to discriminate based on race. Luckily prop 16 did not pass when it somehow made it onto the 2020 ballot. But this brings up a good question of why is discrimination suddenly allowed in government entities?

Here is a recent example of Kamala Harris being purposefully racist through the use of additional social justice buzzwords of Equality and Equity, choosing to deliver hurricane relief aid and funds to victims in Florida primarily [based on race.](https://twitter.com/endwokeness/status/1575945239872737282)

This is not an isolated incident; "[The San Francisco Bicycle Coalition says not to call police about stolen bikes because it hurts 'black and brown' people](https://thepostmillennial.com/san-francisco-bicycle-coalitions-tells-members-not-to-report-stolen-bikes-because-it-hurts-black-and-brown-people)," "

and it's not only woke people and the people who they are trying to help, but [regular everyday people](https://twitter.com/tragicbirdapp/status/1545033499060707330?s=12) who don't know what's going on generally feel that they need to [change their behaviors](https://twitter.com/tragicbirdapp/status/1545107426751438850?s=12) in order to not be racist, sexist, transphobic, etc. even going to sar as to suggest that [white people should not go tanning](https://twitter.com/libsoftiktok/status/1539679020278767618) unless they are an "ally" to the movement. This is a dangerous and society dividing ideology. 


The terms Kamala Harris uses are very important to understand in modern discourse. Equality; meaning equality of opportunity in a merit based system, is what MLK was referring to when using the word in his I Have a Dream speech famously saying, 

"I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin but by the content of their character." 

This speech took place in a time when equality under the law was actually not existent. Today, these terms are *purposefully* misused by the organizers of the many advocates and allies unbeknownst to them, in order to mislead average people (who Lenin called 'useful idiots') in order to achieve 'Equity;' meaning equality of outcome which is to eliminate differential outcomes among racial or other marginalized groups in society, hence the current focus on identity markers and identity politics. It is important to remember; Differences in outcome are not sufficient evidence of discrimination let alone actual discrimination on the books as law. This type of legal discrimination 99% no longer exists in the western world, but many want to bring it back which begs the question; why?

The modern use of 'Equity' is actually a term coming from Marx, and Neo-Marxism from the [Frankfurt school](https://iep.utm.edu/critical-theory-frankfurt-school/) in Germany where much of the new lefts ideas originate from having turned traditional and largely economic Marxism into social Marxism i.e. redefinition of power dynamics, 'dialectic' and ‘critique’ as a means of implementing simultaneously societal-bottom up ideologies as well as economic-top down
 communism into the framework of Plato's centralized philosopher king philosophical model vs Aristotle's decentralized and personal enlightenment philosophical model as explained in the 1971 book "Critical Theory Since Plato" by Hazard Adams, which is of course [available on Amazon.](https://www.amazon.com/Critical-Theory-Since-Plato-Hazard-dp-0155055046/dp/0155055046/ref=dp_ob_title_bk). 

This dichotomy is stark, and critical theorists are now advocating for ridding of society of unwanted and often unnoticed structural and individual biases so that marginalized groups lived experienced are not short changed. This is a commendable goal, and something the right often dismisses while simply advocating for the pulling of bootstraps, however, the methods currently being advocated for on the left at the highest levels of government have now entered into the realm of cultural hegemony. This was in fact expected by those standing against today's renewed racism hidden within critical theory. Now prominent figures like top gender scholar Peter Boghossian have criticisms of critical theory which prevent it from being advocated for seriously, or ethically. That is in addition to James Lindsey and Helen Pluckrose who co authored "Cynical Theories: How Activist Scholarship Made Everything About Race, Gender and Identity – And Why This Harms Everybody" The book was in part a chronicling of the famous stunt they pulled; passing off ridiculous ideas like 'dog parks perpetuate rape culture' and direct Nazi ideology as modern Social Justice publishing these ideas in several top academic and peer reviewed journals proving that not only these ridiculous assertions, but all subjective ideas and arguments are always correct to the social justice movement given they advance the Critical Pedagogy through 'Praxis;' The application and implementation of Critical Theory to education and society. 

This is how the left can continue to claim that 'Critical Theory' is not taught in k-12 schools, and they would be correct, though the Praxis of Critical Theory is clear and universally pervasive as California again is officially suggesting that math classes [should](https://www.nytimes.com/2021/11/04/us/california-math-curriculum-guidelines.html) "use lessons to explore social justice," in order to solve their problem of having some of the nations lowest standardized test scores in math, this is similar to [New York's](https://www.usatoday.com/story/opinion/2018/06/07/fairness-means-lowering-bar-education-column/673198002/) reserving 20% of schools admissions for minority students This is all because equity is necessary to advocate for everywhere. This is where classical liberals and the left writ-large fail to understand the new and growing faction of the woke left; This is why people are [defecting from the left in record numbers](https://twitter.com/RealDSchmidt/status/1538935032571744256?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1538935218228367360%7Ctwgr%5E5bcf4fd40e87694d97abc496617d0b22b2779196%7Ctwcon%5Es2_&ref_url=https%3A%2F%2Fpreview.systems%2Fembed%2FaHR0cHM6Ly90d2l0dGVyLmNvbS9yZWFsZHNjaG1pZHQvc3RhdHVzLzE1Mzg5MzUyMTgyMjgzNjczNjA%2Fcz0xMg%3D%3D), because these arguments are not about the ideas, they are about the Praxis, the implementation of the ideas within society, not arguing about what's best. The end goal of equity of outcome has already been decided. 

In order to make this utopia a reality, actual racism is necessary and widely [accepted](https://twitter.com/libsoftiktok/status/1537827426255917060?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1537827426255917060%7Ctwgr%5E7a20942f4436fdc43a4e68ebaba6417160bf917d%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fpreview.systems%2Fembed%2FaHR0cHM6Ly90d2l0dGVyLmNvbS9saWJzb2Z0aWt0b2svc3RhdHVzLzE1Mzc4Mjc0MjYyNTU5MTcwNjA%2Fcz0xMg%3D%3D) among allies not only as justified, but the right thing to do.

To be clear, [this is what actual racism looks like](https://twitter.com/ampol_moment/status/1532089724680085504?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1532089724680085504%7Ctwgr%5E660840cdfb09902939a02ec8e19ee8bc4a09fa87%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fpreview.systems%2Fembed%2FaHR0cHM6Ly90d2l0dGVyLmNvbS9hbXBvbF9tb21lbnQvc3RhdHVzLzE1MzIwODk3MjQ2ODAwODU1MDQ%2Fcz0xMg%3D%3D). 

This slow and grinding change of societal values is done via subversion of dialectic via new definitions, new terms, and new meanings purposefully meant to drive the creation of ingroups and outgroups, from textbook critical theory and praxis. These are exactly the methods of Mao's youth movement targeting their elders to subvert from the bottom up i.e. 'grassroots movements' who demand things like 'ESG accounting principles' because 'Climate Change is the biggest problem of our time' and that it is such an 'existential issue' it both necessitates and requires simultaneously Lennin's top down approach. This is how we've recently seen the shared ideology and partnerships of grassroot activists with corporate and public-private partnerships which abandon traditional capitalistic values in favor of governmental stakeholder values, and therefore forced equity reflected mandatory compliance with such manipulated narratives.  

This is how and why ‘critical theory’ or 'Praxis' is so important to fully understand at the root level because its these changing definitions which matter most; from ‘justice’ to ‘social justice’ to which now means fairness in (outcomes) of society rather than fairness under the law, and obviously this would mean ‘inclusion’ should take precedence over merit based approaches to help achieve the equality of outcome in the first place, because it’s not about the best outcomes (merit or profits or equal opportunity and treatment under the law, but it's about the most representative outcomes for the new stakeholders who are implementing (top down) actions which cannot be inequitable. i.e. 'equality of outcome', (trimming the tall grass) so that no one is marginalized or oppressed - because these organizations like the UN, the WEF, governments etc. definitely cannot be responsible for any top down approaches that result in inequality. They've forgotten that differences in outcome are not sufficient evidence of discrimination. 

Marx said, "it ought to have been said that with the abolition of class distinctions all social and political inequality arising from them would disappear of itself." Now replace class with race or gender. This is why representation is supposedly so important across all genders, races and identities - because once that is achieved, racism will disappear. 

Advocates of critical race theory like Kendi and De Angelo are directly citing Kimberly Crenshaw, Herbert Marcuse, Kissinger, and others who were living at a time and writing in a world when no one had any idea that millions were dying in Russia, China and Cambodia where these ideas were actually being implemented, these places were seen as (ongoing) great success stories and applauded at the time by postmodernists and a litany of French philosophers like Kant and Foucault who are so often referenced by everyone who promotes these postmodern concepts. 

Finally, California [is now holding back](https://reason.com/2021/05/04/california-math-framework-woke-equity-calculus/) students who are gifted at math, keeping students learning at the same levels for as long as possible, this is precisely what Pol Pot carried out in the Marxist based Cambodian genocide inspired by the Cultural Revolution in China though ended up targeting the  Chinese living in Cambodia. As Dan Carlin from Hardcore history podcast details, The Khmer Group and Pol Pot himself wanted a subsistence based society based on equality meaning they had the power and incentive to go the furthest any society has gone toward implementing the final stages of equality of outcome, they wanted everyone to be the same; The killing started with wealthy individuals with ties to the west, but continued to include intellectuals who often opposed these ideas, then it expanded yet again to include anyone who wore glasses which implied that they had an education which most of the population did not, therefore they were considered enemies of the agrarian movement, and finally it was anyone that stood out for any reason which they could then be considered to be a counter revolutionary, a horrible scar on the face of humanity, it was "the revenge of the ignorant over the educated."- Henri Locard  

For authors writing in the 60's, their praising of equality of outcome is nearly excusable; they had no idea of the atrocities happening in Cambodia to make this nightmare a reality, but those who advocate for these ideas today like Kamala Harris, or Ibram X Kendi, [Oprah](https://www.usatoday.com/story/entertainment/tv/2020/08/06/oprah-winfrey-ibram-x-kendi-discuss-maya-angelou-amy-cooper/3313467001/), and many many more  ignore this until confronted when they use sophistry to dismiss and derail arguments or refuse to debate anyone on the issues, because their ideas are not about correctness in morals, ethics, or their consequences, but are performed through Praxis to achieve equality of outcome.

Gendered and racialized buzzwords are often hiding an ideology which cannot be seen or heard, but one that is being quietly implemented across all facets of society because it appears to be the right thing to do. Sometimes it is right, but most of the time it is the left, and we need to make the distinction between the left and the new left who would like to implement social Marxism in the US like the [founders of Black lives Matter](https://nypost.com/2020/06/25/blm-co-founder-describes-herself-as-trained-marxist/). 

