---
title: ""
output:
  html_document:
    theme: yeti
    sansfont: Georgia
    df_print: paged
    Highlight: Tango
    
    css: styles.css


---

<br>
<br>

<h1>**Makhia Bryant**</h1> 
<h6>
***A text message.***
</h6>

04/22/2021
 <br>

"Another point about the Makhia Bryant convo, how is it that police can’t safely arrest a woman with a knife but they can safely arrest active shooters with automatic weapons?"

I can’t talk much more right now, and this message may sound harsh but I don’t have time to edit it for clarity or without sounding possibly annoyed but that’s not the intention, my intention is for you to see what my obvious reply to a question like this would be, because it takes much more than a phrase the length of a tweet to delve into police behavior in different scenarios and I feel that you could have answered this question from my perspective already. 

First off, your message is not a “point” it’s a question, and as far as I’m concerned we answered this question yesterday. 

But your comparisons need context my dude… like remember all the stuff we talked about yesterday, did you just now decide that there was a way to maybe *quickly toss handcuffs onto the woman doing the stabbing* JUST before the knife entered the woman’s gut, or what? 

Like what are you saying - this woman could have been arrested..? If the cop had attempted to arrested her instead of shot her, the victim would have been *for sure* stabbed and potentially died.

Literally the point of the Bryant case is that the offender was *MID STAB* go back and look at the freeze frame,  and that there’s not much that can be done at that point as far as preventing the stabbing. 

 We then talked about other solutions like the potential police presence escalating things, though the stabbing occurred within 15 seconds of arrival without any direct conversation nor contact, we talked about potential tecnnology in guns/tazers improving, and we talked about letting some number of people literally GET Stabbed in that scenario while a trial run occurs where police either a) do not have guns, or b) that was a social worker that arrived. 

If either a/b happened, we would have a societal understanding that we let the victim get stabbed and potentially die, that’s the experimental group, or the current control group of having police shoot the perpetrator and save the victim to get stabbed.  IF AND ONLY IF The trial runs of a/b taking place in different cities are saving more lives on balance, I would suggest we should switch to those methods of policing, that data would need to be assed after some number of years to see which is saving more lives.

If there is not clear winning strategy in the data, it would need to be taken into account WHO you are trying to protect, the perpetrator or the victim, in the Bryant scenario the perpetrator wielding the knife was killed, in the other scenario, the innocent victim is killed. This is also important, and right now you are seemingly advocating for killing more innocent victims than people committing violent crimes. 

Context matters and your text message is a generic media talking point that makes no sense and is purposefully without context to get in-groups rilled up. Comparing “a woman with a knife” to “active shooter” doesn’t really accomplish all that much because you’re giving zero context for the active shooter, what if they shoot someone then put down their gun, what if they go peacefully, what if they have a conversation with police, what if they are not frantic and *mid shooting*? 

None of these things were occurring in the Bryant case,  are you suggesting an active shooter that potentially gets shot three times by police and is incapacitated but *doesn’t die* Would it be different if Bryant had somehow not died?! That’s luck of the draw currently when you’re shot four times as we saw with my second video example.  In Bryant, the cop literally got out of his car and witnessed someone getting stabbed while having zero direct interaction with the perpetrator or victim. What precisely should happen here?

These things all matter and you’ve given zero context, yet insinuated that the police are doing something wrong in one scenario and right in another without any proof, evidence, qualifiers, or context whatsoever to either scenario. 

If you’re going to make arguments like “police *have at some point in the past* arrested an active shooter” but not “this particular woman with knife” therefore police = bad. I’m not sure what I’m doing saying all this, because I said most of this yesterday and I thought we got somewhere with the analysis. This is the context that matters, and it is a requirement to explain all this to have the conversation in the first place if two people having this conversation are not on the same page about what these options are.

Links mentioned: 
1)"Makhia Bryant Shooting"
2) "Knife-wielding man charge and attacks officer after being shot"

<center>
<iframe width="560" height="315" src="https://www.youtube.com/embed/3MGFoDIUbLo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


<iframe width="560" height="315" src="https://www.youtube.com/embed/KT0KcenH_eQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<center>
<br>